### ISSUE TITLE
Question/possible issue

### ISSUE THREAD

**Issue by cjsauer** [jagi/astro-user#1]
First of all, thank you for setting up this repo for me. It was really helpful. 

Secondly, your code is producing the desired result, but I ran into something strange. I modified your template helper to look like this:

``` javascript
  Template.body.events({
    'click button': function(e, tmpl) {
      var name = tmpl.find('#name').value;
      var item = new Item();
      item.set({
        name: name
      });
      Meteor.call('/item/save', item);
      console.log(item.get('userId'));
    }
  });
```

You can see the `console.log()` call. For some reason, that is printing `null`. Is this desired/expected behavior? It seems like after saving the document, the original object passed into `Meteor.call()` should reflect that change, no?

**Comment by lukejagodzinski** [comment]
You should read more about Meteor itself. It's not an error in Astronomy. It's how Meteor works.

You have to pass a callback function to the method saving a document.

``` js
Meteor.call('/item/save', item, function() {
  console.log(item.get('userId')); // Still null, why?
});
```

As you can see in the comment, it's still `null` in the callback function, why? Because when you send `item` to the Meteor method it gets stringified (to send it over DDP) and the original reference to the object is lost. What you have to do is return a document back from the method:

``` js
// Modify Meteor method
Meteor.methods({
  '/item/save': function(item) { // "item" here is not a reference to the original "item", it's copy send over a DDP protocol
    item.save();
    return item; // Return item back to the client.
  }
});
```

And now:

``` js
Meteor.call('/item/save', item, function(err, returnedItem) {
  console.log(returnedItem.userId);
});
```

I've also updated this repository.

**Comment by cjsauer** [comment]
Thanks again for your help. It was the "stringification" that I was missing. That makes complete sense now; I'm not sure what I was thinking :grin: 

Your point about Meteor methods being asynchronous apparently is only true when there is no callback provided though, [as read by the documentation](http://docs.meteor.com/#/full/meteor_call).

> If you do not pass a callback on the server, the method invocation will block until the method is complete.

EDIT: and thanks for such a great package and your support :+1:

**Comment by lukejagodzinski** [comment]
Oh yes you're right if it goes about asynchronicity. If you are not using a callback function then you have to get returned value, and it will be a document instance returned from the server.

EDIT: You can't use returned value on the client and I think it worked before. I remember that I was using it with saving documents. Maybe they changed something in 1.2.
